version: "3.9"
services:
    api:
        container_name: finansy-api
        build: api/
        command: npm run start:debug
        depends_on:
            - postgres
        environment:
            DATABASE_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
            NODE_ENV: development
            PORT: 3000
        ports: 
            - "3000:3000"
            - "9229:9229"
        volumes: 
            - ./api:/usr/src/app/

    postgres:
        container_name: finansy-postgres
        image: postgres:13.3
        ports: 
            - "5432:5432"
        environment: 
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_DB: ${POSTGRES_DB}